name: ci-docker

on: 
  push:
      branches:
        - "merge_branch"
  pull_request_review:
      branches:
        - "master"      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: docker build 
        run: docker build -t flaskappgithub .
      - name: docker tag
        run: docker tag flaskappgithub ${{ secrets.DOCKER_HUB_USERNAME }}/flaskappgithub
      - name: docker push 
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flaskappgithub
      - name: Run
        run: docker run -d --name mycontainer -p 5000:5000 lagnesh712/flaskappgithub
      - name: docker ps
        run: docker ps 
      - name: docker logs
        run: |
          docker logs mycontainer
          sleep 30
      - name: installing pytest
        run: pip install pytest
      - name: api testing
        run: python3 api_test.py
